import Head from "next/head";
import { type NextPageWithLayout } from "./_app";

// components import
import HeroSection from "@/components/home/HeroSection";
import StaticLayout from "@/components/layouts/StaticLayout";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Top Ten Agro Chemicals</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="grid min-h-screen gap-5">
        <HeroSection />
      </main>
    </>
  );
};

Home.getLayout = (page) => <StaticLayout>{page}</StaticLayout>;

export default Home;
