import { type NextPage } from "next";
import Head from "next/head";
import React from "react";

const Playground: NextPage = () => {
  return (
    <>
      <Head>
        <title>Playground | Topten</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto min-h-screen w-[89vw] max-w-screen-xl pt-28">
        playground
      </div>
    </>
  );
};

export default Playground;
