import Button from "@/components/Button";

import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { toast } from "react-toastify";

const Playground: NextPage = () => {
  return (
    <>
      <Head>
        <title>Playground | Topten</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen py-20 container-res">
        <Button
          intent="primary"
          text="Show toast"
          onClick={() => toast.success("Do a kickflip.")}
        />
      </main>
    </>
  );
};

export default Playground;
