import Button from "@/components/Button";
import { products } from "@/components/data/products";
import ProductTable from "@/components/ProductTable";

import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { toast } from "react-toastify";

const Playground: NextPage = () => {
  return (
    <>
      <Head>
        <title>Playground | Topten</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen gap-10 py-20 container-res">
        <Button
          intent="primary"
          text="Show toast"
          onClick={() => toast.success("Do a kickflip.")}
        />
        <ProductTable products={products} />
      </main>
    </>
  );
};

export default Playground;
