import Head from "next/head";
import { trpc } from "@/utils/trpc";

// components import

const App = () => {
  return (
    <>
      <Head>
        <title>App | Top Ten Agro Chemicals</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main></main>
    </>
  );
};

export default App;
