import Head from "next/head";

const App = () => {
  return (
    <>
      <Head>
        <title>App | Top Ten Agro Chemicals</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="container-res min-h-screen max-w-screen-xl pt-5 pb-10">
        <h1 className="text-sm font-medium text-neutral-700 md:text-base">
          App page
        </h1>
      </main>
    </>
  );
};

export default App;
