import Head from "next/head";

// components import

const App = () => {
  return (
    <>
      <Head>
        <title>App | Top Ten Agro Chemicals</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="min-h-screen max-w-screen-sm container-res">
        <p className="pt-2 text-sm font-medium text-neutral-700 md:text-base">
          User profile successfully registered
        </p>
      </main>
    </>
  );
};

export default App;
